const foodTags = [
    'French cuisine',
    'Chinese cuisine',
    'Japanese cuisine',
    'Italian cuisine',
    'Greek cuisine',
    'Spanish cuisine',
    'Korean cuisine',
    'Mediterranean cuisine',
    'Lebanese cuisine',
    'Moroccan cuisine',
    'Turkish cuisine',
    'Thai cuisine',
    'Indian cuisine',
    'Cajun cuisine',
    'Mexican cuisine',
    'Caribbean cuisine',
    'German cuisine',
    'Russian cuisine',
    'Hungarian cuisine',
    'American cuisine',
    'Spicy food lover',
    'Non-spicy foods only',
    'Dessert lover',
    'Sweets lover',
    'Locavore',
    'Clean eater',
    'Low carbon eater',
    'Meat eater',
    'Chicken lover',
    'Beef lover',
    'Pork lover',
    'No pork',
    'Lamb lover',
    'Duck lover',
    'Seafood lover',
    'Fish lover',
    'Shrimp lover',
    'Vegetarian',
    'Ovo Vegetarian',
    'Lacto Vegetarian',
    'Vegan',
    'Halal',
    'Pollotarian',
    'Flexitarian',
    'Pescatarian',
    'I eat everything',
    'Photographer foodie',
    'Home delivery foodie',
    'Adventurous foodie',
    'Snobbish foodie',
    'Gastronomical foodie',
    'Forever broke foodie',
    'Picky eater',
    'Restaurant',
    'Cafe',
    'Bakery',
    'Boba shop',
    'Breakfast',
    'Lunch',
    'Dinner',
    'Dessert',
    'Snacks',
    'Drinks',
    'Pizza',
    'Sushi',
    'Sashimi',
    'Burgers',
    'Tacos',
    'Ramen',
    'Pho',
    'Vermicelli',
    'Udon',
    'Noodles',
    'Tofu',
    'Croissant',
    'Pasta',
    'Spaghetti',
    'Korean BBQ',
    'Steak',
    'Dim sum',
    'Dumplings',
    'Soup dumplings',
    'Wontons',
    'Gyoza',
    'Hot pot',
    'Paella',
    'BBQ',
    'Skewers',
    'Shawarma',
    'Rice',
    'Fried rice',
    'Boba',
    'Fruit tea',
    'Taro',
    'Thai tea',
    'Roti',
    'Curry',
    'Indian curry',
    'Japanese curry',
    'Thai curry',
    'French fries',
    'Mochi',
    'Cake',
    'Cupcakes',
    'Risotto',
    'Lasagna',
    'Kimchi',
    'Onigiri',
    'Quiche',
    'Brownies',
    'Fried chicken',
    'Soba',
    'Nachos',
    'Biryani',
    'Shabu-shabu',
    'Mac and cheese',
    'Burritos',
    'Tamal',
    'Miso',
    'Soup',
    'Salad',
    'Cheese',
    'Wasabi',
    'Chutneys',
    'Tonkotsu',
    'Guacamole',
    'Quesadilla',
    'Doughnuts',
    'Naan',
    'Bulgogi',
    'Bibimbap',
    'Cookies',
    'Baguettes',
    'Fajitas',
    'Ceviche',
    'Churrasco',
    'Pad thai',
    'Fish and chips',
    'Milkshakes',
    'Mole',
    'Spring rolls',
    'Macarons',
    'Churros',
    'Borek',
    'Bruschetta',
    'Pie',
    'Dondurma',
    'Chorizos',
    'Durian',
    'Yogurt',
    'Sarma',
    'Strawberry',
    'Chocolate',
    'Vanilla',
    'Lemon',
    'Lime',
    'Mint',
    'Banana',
    'Coconut',
    'Cookies and cream',
    'Caramel',
    'Chocolate chip',
    'Green tea',
    'Raspberry',
    'Orange',
    'Funfetti',
    'Cherry',
    'Watermelon',
    'Grape',
    'Mango',
    'Peppermint',
    'Pistachio',
    'Blue moon',
    'Gold',
    'Fudge',
    'Cheesecake',
    'Tiramisu',
    'Mousse',
    'Red velvet',
    'Cream cheese',
    'Apple',
    'Pineapple',
    'Butter cream',
    'Carrot',
    'Blueberry',
    'Pumpkin',
    'Chestnut',
    'Sponge cake',
    'Coffee',
    'Raisin',
    'Grapefruit',
    'Espresso',
    'Americano',
    'Black coffee',
    'Cappuccino',
    'Latte',
    'Macchiato',
    'Mocha',
    'Frappe',
    'Iced coffee',
]

export default foodTags;