const hobbyTags = [
    'Hiking',
    'Skiing',
    'Snowboarding',
    'Soccer',
    'Basketball',
    'Tennis',
    'Badminton',
    'Football',
    'Volleyball',
    'Golf',
    'Cricket',
    'Frisbee',
    'Martial arts',
    'Boxing',
    'Wrestling',
    'Gymnastics',
    'Pool',
    'Darts',
    'Bowling',
    'Concerts',
    'Rave',
    'Music production',
    'Music performance',
    'Listening to music',
    'Reading',
    'Writing',
    'Baking',
    'Cooking',
    'Surfing',
    'Running',
    'Kayaking',
    'Swimming',
    'Skating',
    'Fishing',
    'Scuba diving',
    'Sailing',
    'Painting',
    'Lifting',
    'Hunting',
    'DIY',
    'Art',
    'Watching movies',
    'Binging Netflix',
    'Video gaming',
    'Investing',
    'Climbing',
    'Bouldering',
    'Chess',
    'Poker',
    'Board games',
    'Frat life',
]

export default hobbyTags;