const hobbyTags = [
    'Hiking',
    'Skiing',
    'Snowboarding',
    'Soccer',
    'Basketball',
    'Tennis',
    'Ping pong',
    'Badminton',
    'Football',
    'Volleyball',
    'Golf',
    'Cricket',
    'Frisbee',
    'Crochet',
    'Martial arts',
    'Boxing',
    'Wrestling',
    'Gymnastics',
    'Pool',
    'Darts',
    'Dance',
    'Bowling',
    'Concerts',
    'Rave',
    'Music production',
    'Music performance',
    'Listening to music',
    'Piano',
    'Violin',
    'Guitar',
    'Drums',
    'Singing',
    'Reading',
    'Writing',
    'Baking',
    'Cooking',
    'Surfing',
    'Running',
    'Kayaking',
    'Swimming',
    'Skating',
    'Fishing',
    'Biking',
    'Skateboarding',
    'Scuba diving',
    'Sailing',
    'Painting',
    'Lifting',
    'Hunting',
    'DIY',
    'Art',
    'Watching movies',
    'Binging Netflix',
    'Video gaming',
    'Investing',
    'Climbing',
    'Bouldering',
    'Chess',
    'Poker',
    'Board games',
    'Frat life',
]

export default hobbyTags;